server:
  port: 8768
  context-path: /yibitong

spring:
  profiles:
    active: dev
  application:
    name: yibitong-finance-server

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:1888/eureka/

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      sql-script-encoding: utf-8
      initialSize: 5 #初始化大小
      minIdle: 5 #最小
      maxActive: 100 #最大
      maxWait: 60000 #配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis : 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true #打开PSCache
      maxPoolPreparedStatementPerConnectionSize: 20 #指定每个连接上PSCache的大小
