server:
  port: 8799
  context-path: /yibitong

spring:
  profiles:
    active: dev
  application:
    name: yibitong-user-server

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:1888/eureka/

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      sql-script-encoding: utf-8
      initialSize: 5 #初始化大小
      minIdle: 5 #最小
      maxActive: 100 #最大
      maxWait: 60000 #配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis : 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true #打开PSCache
      maxPoolPreparedStatementPerConnectionSize: 20 #指定每个连接上PSCache的大小
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.yibitong.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    default-executor-type: reuse
    default-statement-timeout: 60000
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  path: logs/yibitong-user-server
  config: classpath:logback.xml